---
- name: Ensure the outage simulator group
  group:
    name: outage-sim
    state: present
- name: Ensure the outage simulator user
  user:
    name: outage-sim
    # For security purposes, we don't ever want this user to be able to log in
    shell: /sbin/nologin
    group: outage-sim
    state: present
- name: Sync the outage simulator binary across to the server
  synchronize:
    src: "{{ outage_sim_binary }}"
    dest: "/usr/bin/tm-outage-sim-server"
- name: Ensure systemd service
  template:
    src: tm-outage-sim-server.jinja2.service
    dest: /etc/systemd/system/tm-outage-sim-server.service
- name: Ensure outage-sim user has the necessary sudo privileges to restart the Tendermint service
  copy:
    src: sudoers-outage-sim
    dest: /etc/sudoers.d/outage-sim
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: (Re)start the outage simulator server
  service:
    name: tm-outage-sim-server
    state: restarted
