[master]
bind = "127.0.0.1:35000"
expect_slaves = 2
expect_slaves_within = "2m"

[slave]
bind = "127.0.0.1:"
master = "127.0.0.1:35000"

[test_network]
    [[test_network.targets]]
    id = "localhost"
    url = "http://127.0.0.1:26657"

[clients]
type = "kvstore-http"
additional_params = ""
spawn = 1
spawn_rate = 1.0
max_interactions = 10
max_test_time = "10m"
request_wait_min = "50ms"
request_wait_max = "50ms"
request_timeout = "5s"
interaction_timeout = "11s"
